dataset:
  name: "synthetic_squat_dataset"
  num_samples: 50000  # Start with 50K samples for faster generation
  sequence_length: 200  # 2 seconds at 100Hz
  sample_rate: 100  # Hz
  output_path: "data/synthetic_squat_dataset.h5"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

simulation:
  timestep: 0.01  # 100Hz simulation
  duration: 3.0  # Total duration per sample (seconds)
  squat_duration: 2.0  # seconds per rep
  rest_duration: 1.0  # seconds between reps
  depth_range: [0.6, 1.0]  # fraction of full squat depth
  speed_range: [0.8, 1.2]  # speed multiplier
  
augmentation:
  # Placement invariance - aggressive sensor position randomization
  position_noise_std: 0.05  # meters
  orientation_noise_std: 15.0  # degrees
  
  # Barometric pressure simulation
  barometric_baseline: 1013.25  # hPa at sea level
  altitude_range: [0, 2000]  # meters above sea level
  pressure_noise_std: 0.5  # hPa
  drift_rate: 0.1  # hPa per minute
  
  # IMU noise modeling
  accel_noise_std: 0.02  # m/s^2
  gyro_noise_std: 0.01  # rad/s
  mag_noise_std: 0.1  # uT
  
  # Fatigue modeling
  fatigue_progression: true
  jitter_increase_rate: 0.001  # per rep
  
form_errors:
  # Inject realistic form errors
  knee_valgus_prob: 0.15
  forward_lean_prob: 0.12
  insufficient_depth_prob: 0.18
  asymmetric_loading_prob: 0.10
  
  # Error magnitudes
  knee_valgus_angle: [5, 20]  # degrees
  forward_lean_angle: [10, 30]  # degrees
  depth_reduction: [0.1, 0.4]  # fraction
  asymmetry_ratio: [0.7, 0.9]  # left/right loading

labels:
  # Multi-task learning targets
  pose_estimation: true  # 3D joint positions
  exercise_classification: true  # squat vs other
  rep_detection: true  # rep boundaries
  form_quality: true  # technique scoring
  cognitive_state: true  # fatigue/focus estimation
